[package]
name = "nilla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { version = "0.1.1", features = ["llvm14-0"] }
inkwell_internals = "0.7.0"
libc = "0.2.146"
